### ISSUE TITLE
How to use gen_rtmp_client?

### ISSUE THREAD

**Issue by phuochau** [KallDrexx/elixir-media-libs#16]
Hi @KallDrexx, Thanks so much for making this library. I'm very impressed with your work. But I'm curious about how can we use the `gen_rtmp_client`? I see `adopter_module` but actually not yet understand it. If you can describe more, it will be helpful, thanks.

**Comment by KallDrexx** [comment]
The best references to understand how to use them is look at the included simple rtmp player app to see how a playback client would be implemented, or simple rtmp proxy to see how a publishing client would be implemented.

Feel free to all any questions related to the examples!!

**Comment by phuochau** [comment]
@KallDrexx Thanks so much for quick response. I will try it and let you know soon (y)

**Comment by phuochau** [comment]
@KallDrexx Seem we can't use with authentication RTMP, right?

**Comment by phuochau** [comment]
Hi @KallDrexx,
I have used the `GenRtmpClient` to publish a stream. As you can see `metadata` is `mp4 in base64`, I can save this raw data to file and be able to play it but can we publish it to RTMP server?

```elixir
{:ok, _client_pid} = GenRtmpClient.start_link(Cls.RTMP.Client, connection_info, key)
GenRtmpClient.start_publish(_client_pid, key, :live)
GenRtmpClient.publish_metadata(_client_pid, key, %Rtmp.StreamMetadata{
      video_height: 720,
      video_width: 1280,
      video_codec: "avc1",
      video_frame_rate: 30,
      video_bitrate_kbps: 1000,
      audio_channels: 2,
      audio_codec: "mp4a",
      audio_bitrate_kbps: 96,
      encoder: metadata
      })
```

P/S: I use `inspect` to print the response from `start_publish` and `publish_metadata`, both are `:ok`.

**Comment by KallDrexx** [comment]
> Seem we can't use with authentication RTMP, right?

I have not implemented authentication yet, but I can definitely investigate adding that in.  If I can find the RTMP protocol for authentication it should be easy to add in.

> I have used the GenRtmpClient to publish a stream. As you can see metadata is mp4 in base64, I can save this raw data to file and be able to play it but can we publish it to RTMP server?

Sorry I"m not totally clear on what you are asking.  The calls you have made are correct, and after you `start_publish` then `publish_metadata`, all you have to do to publish the stream is calling `publish_av_data()` for each audio and video frame.

It sounds like you are trying to save the raw stream to a file and then republish that to another RTMP server.  If I am understanding you correctly then that is not going to be an easy thing to do because the raw file will need to save packet/frame boundaries on each incoming audio and video packet, as well as timestamps for each packet.  There is nothing built into the library for reading or writing audio/video files unfortunately.  

Inspecting `start_publish` and `publish_metadata` calls will always return an `:ok` because they don't do anything directly, but instead send messages to the `GenRtmpClient` base process in order to actually send off the RTMP message.  You should be able to use the `GenRtmpClient` behaviour callbacks to add logging so you know when data is sent and received.

If none of that answers your question I apologize, and maybe rephrasing will help me understand :).

**Comment by phuochau** [comment]
Hi @KallDrexx,
Let me explain by step to step.

1. The web front-end is using `WebSocket` to connect to `Phoenix` as backend. When the socket is connected, we will create RTMP Client by using `GenRtmpClient`. I create it to use as publisher to another RTMP server (`nginx-rtmp`) (I'm using `start_publish()` to start the live stream)
2. I call `getUserMedia` (in frontend) to get video&audio each 1 second and send `base64 data` to `Phoenix`.
3. In Phoenix, the backend got `base64 data` and use `publish_metadata()` to forward raw data to RMTP (`nginx-rtmp`). I'm stuck at here.

I will use `publish_av_data` and will let you know the result, thanks @KallDrexx

**Comment by KallDrexx** [comment]
Ok that makes sense.  Then yes after you call `publish_metadata()` you should be able to forward each audio and video packet that gets received via `publish_av_data` calls.

**Comment by phuochau** [comment]
@KallDrexx but just curious, how can we use 'publish_metadata()' and what is its purpose? because we use 'publish_av_data()' to send raw data, not 'publish_metadata'

**Comment by KallDrexx** [comment]
Traditionally RTMP publishers send an `@setMetadata` RTMP command to the server any time details about the video/audio stream are updated.  The details include video resolution, audio/video bitrate, encoder information, codec information, etc..  The information it sends is pretty free form overall and different encoders send different metadata information.

When an RTMP server receives this metadata it relays it to all subscribed clients via another RTMP command.  This way any playback clients know all the metadata information for the video and can adjust accordingly.  Some playback clients may ignore this but most require at least some basic metadata.  I do not know if Nginx RTMP requires metadata or not.

Traditionally these metadata values do not change and only need to be sent once at the very beginning of the stream.

Page 49 of the [RTMP Specification](https://www.adobe.com/content/dam/Adobe/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf) shows this flow.

**Comment by phuochau** [comment]
@KallDrexx Thanks so much, my boss just said we will build the desktop app and integrate RTMP client. I will take a look your solution in free time and try to contribute more for you :)
