### ISSUE TITLE
Saving Raw Stream Data

### ISSUE THREAD

**Issue by nathanjohnson320** [KallDrexx/elixir-media-libs#19]
Hello, I'm not sure if these packages are still used but I am modifying the simple rtmp server to save raw data from an OBS rtmp stream (the video and audio data) but I'm not sure what format the "data" bytes are in the event here: https://github.com/KallDrexx/elixir-media-libs/blob/master/apps/simple_rtmp_server/lib/simple_rtmp_server/worker.ex#L223

any guidance would be much appreciated :+1:

**Comment by KallDrexx** [comment]
Sorry, I meant to get back to this an never did!

Fwiw this code isn't used (or at least isn't to my knowledge).  I royally messed up the architecture trying to solve a timing bug (thinking it was a performance bug and not realizing it was a RTMP decoding bug).  Since I didn't understand why the bug was fixed and I thought it was performance I moved on to recreating the library in Rust.  I have now realized my mistake.

That being said, the code you are looking at writes the raw bytes in no explicit format.  Every byte that comes in is written to the input log file in the order it was received.  This is achieved because RTMP packets have length information in them, so you can pretty easily read the byte stream one rtmp chunk at a time, but you have to be aware that each log file is one direction only (so it's not a full back and forth conversation, but input only or output only).

Example code to read this can be found with the following CLI tool: https://github.com/KallDrexx/elixir-media-libs/tree/master/apps/rtmp_reader_cli

**Comment by nathanjohnson320** [comment]
@KallDrexx ah thanks for the response that makes sense :+1:
